fc_platform:
    resource: "@FCPlatformBundle/Resources/config/routing.yml"
    prefix:   /
    
core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

# fos_js_routing:
#     resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
#     prefix:    /fos
