core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

fc_platform:
    resource: "@FCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

# fos_js_routing:
#     resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
#     prefix:    /fos
